# Generated by Django 4.1.7 on 2023-04-02 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('imguser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.userprofile')),
            ],
        ),
    ]
