# Generated by Django 4.1.7 on 2023-04-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
