# Generated by Django 4.1.7 on 2023-04-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('imgid', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
